import Head from 'next/head';
import { Row } from 'antd';

import SearchUser from '../components/Users/FindUser/FindUser';
import Welcome from "../components/Welcome/Welcome";
import {useEffect} from "react";
import {setMessagesData} from "../store/messagesSlice";
import {socket} from "./_app";
import {useDispatch} from "react-redux";
import MessageAlert from "../components/Custom/MessageAlert/MessageAlert";


export default function Home() {
    const dispatch = useDispatch();

    useEffect(() => {
        socket.on("message", (data: any) => {
            MessageAlert();
            dispatch(setMessagesData(data));
        })
    }, [])

  return (
    <div className="h-100">
      <Head>
        <title>Talk Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Row className="w-100 h-100">
        <Welcome />
        <SearchUser />
      </Row>
   </div>
  )
}
