import Head from 'next/head';
import { Row } from 'antd';

import SearchUser from '../components/Users/FindUser/FindUser';
import Welcome from "../components/Welcome/Welcome";

export default function Home() {

  return (
    <div style={{
        height: "100%"
      }}>
      <Head>
        <title>Talk Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Row style={{
        width: "100%",
        height: "100%"
      }}>
        <Welcome />
        <SearchUser />
      </Row>
   </div>
  )
}
